---
title: "dplyer_example"
author: "Yineng Chen"
date: "2019/9/19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
```

## import Data

```{r}
options(tibble.print_min = 3)

litters_data = read_csv("./data/FAS_litters.csv",
                      col_types = "ccddiiii")
litters_data = janitor::clean_names(litters_data)

pups_data = read_csv("./data/FAS_pups.csv",
                       col_types = "ciiiii")
pups_data = janitor::clean_names(pups_data)
```

## To select a subset of columns --- select()
1. select specific columns
```{r}
select(litters_data, group, litter_number, gd0_weight, pups_born_alive)
```

1. select a range of columns
```{r}
select(litters_data, group:gd_of_birth)
```

1. select colums to remove
```{r}
select(litters_data, -pups_survive)
```

1. rename variables as part of this process:

```{r}
select(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```

11. use **rename** instead of **select**. This will rename the variables you care about, and keep everything else:
```{r}
rename(litters_data, GROUP = group, LiTtEr_NuMbEr = litter_number)
```


